### ISSUE TITLE
AttributeError: 'dict_keys' object has no attribute 'sort'

### ISSUE THREAD

**Issue by bucoyas** [castelao/seabird#44]
Hey,

I am attempting to convert a .CNV file to .nc  using:
`seabird cnv2nc 1510105.CNV`

 and I keep getting this error:
`AttributeError: 'dict_keys' object has no attribute 'sort'`

`Saving on 1510105.CNV
DEBUG:root:Openning file: 1510105.CNV
Saving netcdf output file: 1510105.CNV
Traceback (most recent call last):
 
 File "/usr/local/bin/seabird", line 11, in <module>
    sys.exit(cli())
 
File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)

 File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)

 File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
 
 File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
 
 File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  
File "/usr/local/lib/python3.5/dist-packages/seabird/cli.py", line 55, in nc
    cnv2nc(data, outputfilename)
 
 File "/usr/local/lib/python3.5/dist-packages/seabird/netcdf.py", line 35, in cnv2nc
    A.sort()
`

**Comment by castelao** [comment]
@bucoyas , thanks for reporting that. Sorry for the delay. The new release, 0.10.4, should resolve that.

I'll keep this issue open until I have the chance to write a test to run `seabird cnv2nc`
