### ISSUE TITLE
Errors using commands: cnv2nc, cnvdump, ctdqc

### ISSUE THREAD

**Issue by ghost** [castelao/seabird#69]
Hello!
I am trying to get the Seabird python module to work that I installed using PIP. In command line when i write "seabird," it shows seabird help. But when using seabird commands like "C:\seabird cnvdump sbe19_test.cnv" I get the errors shown below. I am using Miniconda3, Python 3.9.1, NetCDF is installed, also NumPy. What could be the problem? Maybe I should uninstall Miniconda and install the Anaconda?

`Traceback (most recent call last):
  File "c:\programdata\miniconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\programdata\miniconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\Scripts\seabird.exe\__main__.py", line 7, in <module>
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\programdata\miniconda3\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\programdata\miniconda3\lib\site-packages\seabird\cli.py", line 31, in dump
    data = fCNV(inputfilename)
  File "c:\programdata\miniconda3\lib\site-packages\seabird\cnv.py", line 574, in __init__
    super(fCNV, self).__init__(text, defaults)
  File "c:\programdata\miniconda3\lib\site-packages\seabird\cnv.py", line 58, in __init__
    self.rule, self.parsed = load_rule(self.raw_text)
  File "c:\programdata\miniconda3\lib\site-packages\seabird\utils.py", line 77, in load_rule
    rule = json.loads(text.decode('utf-8'), encoding="utf-8")
  File "c:\programdata\miniconda3\lib\json\__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'`

**Comment by pcastilloq** [comment]
Here is the answer. https://github.com/castelao/seabird/issues/65#issuecomment-792709645
