### ISSUE TITLE
fCNV JSONDecoder error

### ISSUE THREAD

**Issue by fpahernandez** [castelao/seabird#72]
Using fCNV to read a .cnv profile:

import sys
import numpy as np
import seabird
from seabird.cnv import fCNV
Fic = DirHydro + DirABR + "Est11__SouthBahia.cnv"
profile = fCNV(Fic)

Error description:

Traceback (most recent call last):

  File "/var/folders/s5/l4k15wz11tj840w0qyj2ksph0000gn/T/ipykernel_9928/2120108936.py", line 1, in <module>
    profile = fCNV(Fic)

  File "/Users/fhernandez/opt/anaconda3/envs/dev39/lib/python3.10/site-packages/seabird/cnv.py", line 574, in __init__
    super(fCNV, self).__init__(text, defaults)

  File "/Users/fhernandez/opt/anaconda3/envs/dev39/lib/python3.10/site-packages/seabird/cnv.py", line 58, in __init__
    self.rule, self.parsed = load_rule(self.raw_text)

  File "/Users/fhernandez/opt/anaconda3/envs/dev39/lib/python3.10/site-packages/seabird/utils.py", line 77, in load_rule
    rule = json.loads(text.decode('utf-8'), encoding="utf-8")

  File "/Users/fhernandez/opt/anaconda3/envs/dev39/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)

TypeError: JSONDecoder.__init__() got an unexpected keyword argument 'encoding'

USING:
MAcOS 12.6.1
Anaconda Navigator 2.3.2
cotede 0.23.7
seabird 0.11.5
python 3.10.6

**Comment by castelao** [comment]
Thanks for reporting that. You'll need to update to seabird-0.12 or later.
You can do that with PIP or wait a few minutes for conda-forge to update
itself.

Cheers,

**Comment by fpahernandez** [comment]
Thanks a lot. I updated usind "conda update seabird" on my environnement. It works. By the way, my .cnv files do not contain lon/lat (they are recorded only onto the log doc from the sea campaign). Is there a way to update the cnv file with lon/lat data? Thanks again for your effort for the community.
