### ISSUE TITLE
'netCDF4' is not defined

### ISSUE THREAD

**Issue by larissafranklin23** [castelao/seabird#77]
C:\Users\Larissa Franklin\Desktop\ACADÊMICO\LADCEN\COLACMAR_CBO_2024\Dados\Setembro\norte>seabird cnv2nc Hotin.cnv
netCDF4 is not available.
Saving on Hotin.nc
Saving netcdf output file: Hotin.nc
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Scripts\seabird.exe\__main__.py", line 7, in <module>
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\seabird\cli.py", line 59, in nc
    cnv2nc(data, outputfilename)
  File "C:\Users\Larissa Franklin\AppData\Local\Programs\Python\Python311\Lib\site-packages\seabird\netcdf.py", line 38, in cnv2nc
    nc = netCDF4.Dataset(filename, "w", format="NETCDF4")
         ^^^^^^^
NameError: name 'netCDF4' is not defined

I'm trying to run the Hotin.cnv and other CTD files, but I'm encountering an error. Could you provide some tips on how to fix it?
And once I had run it and it was ok.

**Comment by VeckoTheGecko** [comment]
You need to install the optional netcdf dependency:

`pip install 'seabird[CDF]'`

Or do `pip install netcdf4` separately
